version: '3.8'
services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: seemyfamily
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d
    ports:
      - "3307:3306"
